/*
<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
*/

pub fn solution() {
    let mut sum = 0;
    let mut a = 1;
    let mut b = 2;
    let limit = 4_000_000;
    while b <= limit {
        if b % 2 == 0 {
            sum += b;
        }
        let temp = a + b;
        a = b;
        b = temp;
    }

    assert_eq!(sum, 4613732 as i32);
    
    println!("[P2] The sum of the even-valued Fibonacci terms below {} is {}", limit, sum);
}
